### ISSUE TITLE
Probably shouldn't call flush_all()

### ISSUE THREAD

**Issue by sethhall** [ncsa/bro-is-darknet#1]
As a purely library-type script, calling flush_all() may cause Bro to have unexpected side-effects when a user has it loaded.

https://github.com/ncsa/bro-is-darknet/blob/22f4977426f24535d2127e96c252ef7494279d20/scripts/main.bro#L54

**Comment by JustinAzoff** [comment]
Ah yes.. and I need to create a real log file and not use Reporter::info too..

Fortunately that code path isn't hit very often.

**Comment by JustinAzoff** [comment]
Resolved in https://github.com/ncsa/bro-is-darknet/pull/2
