### ISSUE TITLE
Tests breaks on newer versions of zeek - calls bro and bro-cut binarys instead of zeek

### ISSUE THREAD

**Issue by dataolle** [ncsa/bro-is-darknet#5]
Installation failes when running unit tests using zkg.
Looks like the unit tests are using old binarys "bro" and "bro-cut".
This is causeing installation to fail using zkg since these binarys are symlinks to zeek-wrapper now.
Easy to fix is to remove the symlink to the actual binarys instead but this should really be fixed in the package.

Running zeek version 3.1.5

**Comment by JustinAzoff** [comment]
Fixed in 91bec43, tagged as 1.0
